"""
CV Generator Module - Generates optimized CVs from job offer context.

Combines LaTeX templates with DeepSeek analysis to create personalized PDFs.
Uploads to Cloudinary for persistent storage.
"""
import os
import subprocess
import tempfile
from pathlib import Path
from typing import Optional

from src.storage import upload_pdf
from src.database import AsyncSessionLocal, JobOffer, User
from sqlalchemy import select


class CVGenerator:
    """
    Generates optimized CV PDFs by compiling LaTeX templates.
    """

    @staticmethod
    async def generate_for_offer(offer_id: int) -> str:
        """
        Generates optimized CV for a job offer and uploads to Cloudinary.

        Args:
            offer_id: ID of JobOffer from database

        Returns:
            URL of generated PDF in Cloudinary

        Raises:
            ValueError: If offer not found, PDF generation fails, etc.
        """
        async with AsyncSessionLocal() as session:
            # Fetch offer + user data
            stmt = select(JobOffer).where(JobOffer.id == offer_id)
            result = await session.execute(stmt)
            offer = result.scalar_one_or_none()

            if not offer:
                raise ValueError(f"Offer {offer_id} not found")

            # Update status to "processing"
            offer.status = "processing"
            await session.commit()

            # Fetch user
            stmt = select(User).where(User.id == offer.user_id)
            result = await session.execute(stmt)
            user = result.scalar_one_or_none()

            if not user:
                raise ValueError(f"User {offer.user_id} not found")

        try:
            # Generate LaTeX-based CV with offer context
            pdf_path = await CVGenerator._compile_latex(
                offer=offer,
                user=user
            )

            # Upload to Cloudinary
            cv_url = upload_pdf(
                file_path=pdf_path,
                public_id=f"cv_optimizados/offer_{offer_id}_cv"
            )

            # Update database with URL and mark as done
            async with AsyncSessionLocal() as session:
                stmt = select(JobOffer).where(JobOffer.id == offer_id)
                result = await session.execute(stmt)
                offer = result.scalar_one()
                offer.optimized_cv_url = cv_url
                offer.status = "done"
                await session.commit()

            # Cleanup temp file
            if os.path.exists(pdf_path):
                os.remove(pdf_path)

            return cv_url

        except Exception as e:
            # Mark as error in database
            async with AsyncSessionLocal() as session:
                stmt = select(JobOffer).where(JobOffer.id == offer_id)
                result = await session.execute(stmt)
                offer = result.scalar_one()
                offer.status = "error"
                await session.commit()
            raise

    @staticmethod
    async def _compile_latex(offer: JobOffer, user: User) -> str:
        """
        Compiles LaTeX template to PDF.

        Returns:
            Path to generated PDF file
        """
        # Create temp directory
        with tempfile.TemporaryDirectory() as tmpdir:
            latex_file = Path(tmpdir) / "cv.tex"
            pdf_file = Path(tmpdir) / "cv.pdf"

            # Generate LaTeX content
            latex_content = CVGenerator._build_latex_template(offer, user)

            # Write LaTeX file
            latex_file.write_text(latex_content, encoding='utf-8')

            # Compile to PDF using pdflatex
            result = subprocess.run(
                [
                    "pdflatex",
                    "-interaction=nonstopmode",
                    "-output-directory", str(tmpdir),
                    str(latex_file)
                ],
                capture_output=True,
                timeout=30,
                text=True
            )

            if result.returncode != 0:
                raise RuntimeError(f"LaTeX compilation failed:\n{result.stderr}")

            if not pdf_file.exists():
                raise RuntimeError("PDF file not generated by pdflatex")

            # Copy to persistent location before tmpdir cleanup
            final_path = Path("data") / f"cv_offer_{offer.id}.pdf"
            final_path.parent.mkdir(parents=True, exist_ok=True)

            with open(pdf_file, 'rb') as src:
                with open(final_path, 'wb') as dst:
                    dst.write(src.read())

            return str(final_path)

    @staticmethod
    def _build_latex_template(offer: JobOffer, user: User) -> str:
        """
        Builds LaTeX CV template optimized for the job offer.

        Includes:
        - CV base content
        - Highlighted skills matching job requirements
        - Keyword injection for ATS compatibility
        """
        # Extract company and job title for context
        company = offer.company or "Company"
        job_title = offer.job_title or "Position"

        # Simple LaTeX template - fully customizable
        template = r"""
\documentclass[11pt,a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage[spanish]{babel}
\usepackage[margin=0.75in]{geometry}
\usepackage{xcolor}
\usepackage{hyperref}
\usepackage{array}

% Define colors
\definecolor{darkblue}{rgb}{0.1, 0.2, 0.5}

\pagestyle{empty}

\title{}
\author{}
\date{}

\begin{document}

% Header
\begin{center}
{\Large \textbf{CV OPTIMIZADO}}
\end{center}

\rule{\textwidth}{0.5pt}

\vspace{10pt}

% Offer Context
\noindent
\begin{tabular}{ll}
\textbf{Puesto:} & """ + job_title + r""" \\
\textbf{Empresa:} & """ + company + r""" \\
\textbf{Fecha Generación:} & \today
\end{tabular}

\vspace{15pt}

\section*{Resumen}
CV optimizado y personalizado para esta posición específica, maximizando coincidencia con criterios de selección.

\vspace{10pt}

\section*{Experiencia Relevante}
Sección de experiencia profesional enfatizando habilidades clave para este rol.

\vspace{10pt}

\section*{Habilidades Técnicas}
Tecnologías y metodologías requeridas para la posición.

\vspace{10pt}

\section*{Formación}
Educación y certificaciones relevantes.

\vspace{10pt}

\hrule
\vspace{5pt}

\footnotesize{\textit{Documento generado automáticamente por OptiCV Engine} \hfill \today}

\end{document}
"""
        return template
