"""Add preferred_language to users table

Revision ID: 39e26c8816eb
Revises: 005_remove_scoring_details
Create Date: 2026-04-29 17:19:27.567646

"""
from alembic import op
import sqlalchemy as sa


revision = '39e26c8816eb'
down_revision = '005_remove_scoring_details'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_language', sa.String(5), server_default='es', nullable=False))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_language')
    # ### end Alembic commands ###
